os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - composer require "squizlabs/php_codesniffer=*"
  - phpenv rehash
script:
  - php vendor/bin/phpcs --standard=PSR2 app
